services:
  db:
    image: postgres:15
    container_name: lab2_db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mywebapp_db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d mywebapp_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - lab2_net

  web:
    build: .
    container_name: lab2_app
    restart: always
    volumes:
      - ./config/config.docker.json:/etc/mywebapp/config.json:ro
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lab2_net

  nginx:
    image: nginx:latest
    container_name: lab2_nginx
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    networks:
      - lab2_net

networks:
  lab2_net:
    driver: bridge
volumes:
  db_data:
