name: CD Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy to Target Node
    environment: production
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no student@${{ secrets.HOST_IP }} << 'EOF'
            cd ~/software_deployment/lab3
            git pull
            sudo systemctl restart mywebapp
          EOF

      - name: Verification
        run: |
          curl -f http://${{ secrets.HOST_IP }}:8080/ || (echo "Deployment failed" && exit 1)